### ISSUE TITLE
Host your project on a server to show it for any viewer or prospective employer

### ISSUE THREAD

**Issue by Yuri-B** [orsolyabus/yoga_room#11]
If you have time, try to host your project on Github pages ( https://pages.github.com/ ), so that people could see it working online. That way, not only other programmers can see your work but non-technical people as well.

If you need a server, you have several options such as Amazon Web Services : [https://aws.amazon.com/free/?awsf.Free%20Tier%20Types=categories%2312monthsfree](url)

**Note :** creating Github pages and hosting sites can take over a day's work but it can be beneficial, especially if you are looking for jobs or collaboration opportunities

**Comment by orsolyabus** [comment]
thank you for the suggestion, i have it on Heroku, just added the link to the readme.
